version: "2.29" # docker compose version

networks: # setup network
  internal:
    ipam:
      driver: default
      config:
        - subnet: "192.168.1.0/24"

services: # setup containers

  webapp: # container name
    build:
      context: . # draws from a directory or repo URL
      dockerfile: image/dockerfile # relative filepath to a dir containing the dockerfile
    ports:
      - "8000:80" # <host port>:<container port>
    depends_on:
      - database # will wait for this to start before starting
    networks:
      internal:
        ipv4_addr: "192.168.1.10"

  database: # container name
    image: mysql:latest # just draw from the official container of mysql
    environment: # env variables
      - MYSQL-DATABASE=shopii_db
      - MYSQL_ROOT_PASSWORD=d@gg3R
      - MYSQL_USER=admin2
      - MYSQL_PASSWORD=id0ntkn0w
    restart: unless-stopped
    networks:
      - internal # this is the name for the internal network

  phpmyadmin: # debugging interface name
    image: phpmyadmin # draws from the official container of phpmyadmin
    ports:
      - "8001:80" # <host port>:<container port>
    environment: # env vars
      - ARBITRARY=1
      - HOST=database
      - PORT=3306
    networks:
      - internal



