FROM php:8.2.4-apache

# update system + install mysqli
RUN sudo apt update
RUN sudo docker-php-ext-install mysqli pdo_mysqli
RUN sudo docker-php-ext-enable mysqli

# this is the blueprint for the containers
